name: Docker Image CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Installer Python et les dépendances
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install flake8 pytest pylint
      - name: Analyser le code avec flake8
        run: |
          source venv/bin/activate
          flake8 Program.py
      - name: Analyser le code avec pylint
        run: |
          source venv/bin/activate
          pylint Program.py
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest

